name: MACOS => Build and Test (clang)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup x86_64 Homebrew
      run: |
        cd /usr/local
        mkdir homebrew
        curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
        eval "$(/usr/local/homebrew/bin/brew shellenv)"
        brew update
        
    - name: Install deps
      run: |
        eval "$(/usr/local/homebrew/bin/brew shellenv)"
        brew install llvm
        brew install clang-build-analyzer
        brew install --cask clay
        brew install boost
        echo "/usr/local/opt/llvm/bin" >> $GITHUB_PATH

    - name: Build scarlet
      run: |
        arch -x86_64 /bin/zsh -c 'mkdir -p build && cd build && cmake -DCMAKE_CXX_COMPILER=clang++ .. && make'
    
    - name: Test scarlet
      run: |
        arch -x86_64 /bin/zsh -c 'mkdir -p build && cd build && cmake -DCMAKE_CXX_COMPILER=clang++ .. && make test-scarlet'
