name: MACOS => Build and Test (gcc)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-13
    env:
      HOMEBREW_PREFIX: /usr/local
      CC: gcc
      CXX: g++
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Install deps
      run: |
        brew update
        brew install gcc
        brew install --cask clay
        brew install boost

    - name: Build scarlet
      run: |
        arch -x86_64 /bin/zsh -c 'mkdir -p build && cd build && cmake -DCMAKE_CXX_COMPILER=g++ .. && make'
    
    - name: Test scarlet
      run: |
        arch -x86_64 /bin/zsh -c 'mkdir -p build && cd build && cmake -DCMAKE_CXX_COMPILER=g++ .. && make test-scarlet'
