name: MACOS => Build and Test (clang)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install deps and Setup X86_64 environment
      run: |
        brew update
        brew install clang boost clang-build-analyzer
        brew install --cask clay
        arch -x86_64 zsh
        
    - name: Build scarlet
      run: |
        mkdir -p build && cd build && cmake -DCMAKE_CXX_COMPILER=clang++ .. && make

    - name: Test scarlet
      run: |
        mkdir -p build && cd build && cmake -DCMAKE_CXX_COMPILER=clang++ .. && make test-scarlet
