name: MACOS => Build and Test (gcc)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-13
    env:
      HOMEBREW_PREFIX: /usr/local
      CC: gcc-13
      CXX: g++-13
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Install deps
      run: |
        brew update
        brew install gcc@13
        brew install --cask clay
        brew install boost

    - name: Build scarlet
      run: |
        arch -x86_64 /bin/zsh -c 'export CC=gcc-13 && export CXX=g++-13 && mkdir -p build && cd build && cmake .. && make'
    
    - name: Test scarlet
      run: |
        arch -x86_64 /bin/zsh -c 'export CC=gcc-13 && export CXX=g++-13 && mkdir -p build && cd build && cmake .. && make test-scarlet'