name: MACOS => Build and Test (clang)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install deps
      run: |
        brew install --prefix /usr/local llvm
        brew install --prefix /usr/local clang-build-analyzer
        brew install --prefix /usr/local --cask clay
        brew install --prefix /usr/local boost
        echo "/usr/local/opt/llvm/bin" >> $GITHUB_PATH

    - name: Build scarlet
      run: |
        arch -x86_64 /bin/zsh -c 'mkdir -p build && cd build && cmake -DCMAKE_CXX_COMPILER=clang++ .. && make'
    
    - name: Test scarlet
      run: |
        arch -x86_64 /bin/zsh -c 'mkdir -p build && cd build && cmake -DCMAKE_CXX_COMPILER=clang++ .. && make test-scarlet'
