name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install deps
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt update
        sudo apt install gcc-13 g++-13 libboost-all-dev
        
    - name: Build scarlet
      run: |
        mkdir -p build && cd build && cmake .. && make

    - name: Test scarlet
      run: |
        mkdir -p build && cd build && cmake .. && make test-scarlet
